## YAML Template.
---
Kafka:
   zkHosts: "nn1.netangels.net:2181,nn2.netangels.net:2181,rm1.netangels.net:2181" 
   topic: "oddeye"
   tsdbtopic: "oddeyetsdb"
   zkRoot: "/storm_oddeye"
   zkKey: "oddeye-staus"
   zkKeyTSDB: "oddeye-stausTSDB"
   
Topology:    
    DisplayName: "KafkaHbaseTopology"
    NumWorkers: 2
    SpoutParallelism_hint: 2
    TSDBMsgBoltParallelism_hint: 2    
    MsgBoltParallelism_hint: 1    
    MetaBoltParallelism_hint: 1    
    Debug: false
    
