## YAML Template.
---
Kafka:
   zkHosts: "nn1.netangels.net:2181,nn2.netangels.net:2181,rm1.netangels.net:2181"       
   tsdbtopic: "oddeyetsdb"
   zkRoot: "/storm_oddeye"
   zkKey: "oddeye-staus"
   zkKeyTSDB: "oddeye-TSDBstat"
   
ErrorKafka:
    bootstrap.servers: "node0.netangels.net:9092,node1.netangels.net:9092,node2.netangels.net:9092" 
    topic: "errors"
    
   
Tsdb:
  zkHosts: "nn1.netangels.net:2181,nn2.netangels.net:2181,rm1.netangels.net:2181"   
  metatable: test_oddeye-meta
  errorstable: test_oddeye-errors
  errorshistorytable: test_oddeye-error-history
  tsd.core.auto_create_metrics: true
  tsd.storage.enable_compaction: false
  tsd.storage.hbase.data_table: test_tsdb
  tsd.storage.hbase.uid_table: test_tsdb-uid
   
Topology:    
    topologi.display.name: "OddeyeTimeSeriesTopology"
    NumWorkers: 3
    SpoutParallelism_hint: 1
    ParseMetricBoltParallelism_hint: 2
    WriteToTSDBseriesParallelism_hint: 6
    CompareBoltParallelism_hint: 6
    CalcRulesBoltParallelism_hint: 6
    ErrorKafkaHandlerParallelism_hint: 3
    CheckSpecialErrorBoltParallelism_hint: 3
    FilterForLastTimeBoltParallelism_hint: 3
    CheckLastTimeBoltParallelism_hint: 6
#    TSDBMsgBoltParallelism_hint: 4
#    WarningParallelism_hint: 8
    Debug: false
    DisableCheck: false
    topology.message.timeout.secs: 30
    topology.max.spout.pending: 1024
