## YAML Template.
---
Kafka:
   zkHosts: "pve4.office.loc:2181"       
   tsdbtopic: "oddeyetsdb"   
   zkRoot: "/storm_oddeye"
   zkKey: "oddeye-staus"
   zkKeyTSDB: "oddeye-TSDBstat"
   
ErrorKafka:
    bootstrap.servers: "pve1.office.loc:9092,pve2.office.loc:9092,pve3.office.loc:9092" 
    topic: "errors"

KafkaSemaphore:
   zkHosts: "pve4.office.loc:2181"       
   topic: "semaphore"   
   zkRoot: "/semaphore_oddeye"
   zkKey: "semaphore-staus"       
   
   
Tsdb:
  zkHosts: "pve4.office.loc:2181"   
  hbase.rpcs.batch.size: 4096 
  metatable: oddeye-meta
  errorstable: oddeye-errors
  errorshistorytable: oddeye-error-history
  errorslasttable: oddeye-error-last
  usertable: oddeyeusers  
  consumptionusertable: oddeye-consumption  
  optionstable: oddeyeOptionstable  
  messageprice: 1.16674133811e-06  
  
  tsd.core.auto_create_metrics: true
  tsd.storage.enable_compaction: false
  tsd.storage.hbase.data_table: test_tsdb
  tsd.storage.hbase.uid_table: test_tsdb-uid

   
mail:
    from: noreply@oddeye.co
    smtp.host: mail.netangels.net
    smtp.auth: true
    smtp.port: 25
    mail.user: noreply@oddeye.co
    mail.password: Rembo3Rembo4
    
Topology:    
    topologi.display.name: "OddeyeTimeSeriesTopology"
    NumWorkers: 3
    SpoutParallelism_hint: 1
    SpoutSemaphoreParallelism_hint: 1
    ParseMetricBoltParallelism_hint: 1
    SemaforProxyBoltParallelism_hint: 1
    WriteToTSDBseriesParallelism_hint: 3
    CompareBoltParallelism_hint: 3
    CalcRulesBoltParallelism_hint: 3
    ErrorKafkaHandlerParallelism_hint: 3
    CheckSpecialErrorBoltParallelism_hint: 1
    UserBalaceCalcBoltParallelism_hint: 1
   
    MetricErrorToHbaseParallelism_hint: 1
    SendNotifierBoltParallelism_hint: 3    
#    TSDBMsgBoltParallelism_hint: 4
#    WarningParallelism_hint: 8
    Debug: false
    DisableCheck: false
    topology.message.timeout.secs: 30
    topology.max.spout.pending: 1024
