## YAML Template.
---
Kafka:
   zkHosts: "nn1.netangels.net:2181,nn2.netangels.net:2181,rm1.netangels.net:2181" 
   topic: "oddeye"
   tsdbtopic: "oddeyetsdb"
   zkRoot: "/storm_oddeye"
   zkKey: "oddeye-staus"
   zkKeyTSDB: "oddeye-stausTSDB"
   
Tsdb:
  zkHosts: "nn1.netangels.net:2181,nn2.netangels.net:2181,rm1.netangels.net:2181"   
  tsd.core.auto_create_metrics: true
  tsd.storage.hbase.data_table: test_tsdb
  tsd.storage.hbase.uid_table: test_tsdb-uid
   
Topology:    
    DisplayName: "KafkaHbaseTopology"
    NumWorkers: 3
    SpoutParallelism_hint: 3
    TSDBMsgBoltParallelism_hint: 3    
    MsgBoltParallelism_hint: 1    
    MetaBoltParallelism_hint: 1    
    Debug: false
    
