## YAML Template.
---
Kafka:
   zkHosts: "nn1.netangels.net:2181,nn2.netangels.net:2181,rm1.netangels.net:2181" 
   topic: "oddeye"
   tsdbtopic: "oddeyetsdb"
   zkRoot: "/storm_oddeye"
   zkKey: "oddeye-staus"
   zkKeyTSDB: "oddeye-stausTSDB"
   
Topology:
    DisplayName: "KafkaHbaseTopology"
    SpoutParallelism_hint: 1
    MsgBoltParallelism_hint: 1
    TSDBMsgBoltParallelism_hint: 1
    MetaBoltParallelism_hint: 1
    NumWorkers: 1
#    SpoutParallelism_hint: 1
#    MsgBoltParallelism_hint: 1
#    MetaBoltParallelism_hint: 1
#    NumWorkers: 1

    Debug: false
    
